### ISSUE TITLE
Removed style of table row after pasting the content in editor

### ISSUE THREAD

**Issue by kundanSinghFworks** [froala/ember-froala-editor#145]
When we are pasting some content from other website, After pasted the content I see style of **table row** tag got removed.

https://github.com/froala/ember-froala-editor/assets/96573042/a4aa9cb2-d601-4440-91db-c95e708a540d

 **HTML content file :-** [content.txt](https://github.com/froala/ember-froala-editor/files/11551824/content.txt)

Same thing copied to other rich text editor, It is working fine.

**Copied table row element screenshot in website from where we copy:-** 

<img width="1073" alt="image" src="https://github.com/froala/ember-froala-editor/assets/96573042/96cf1964-0b42-4e5e-8c85-a2881e4c32a3">

**Pasted table row element screenshot in Froala:-** 

<img width="1073" alt="image" src="https://github.com/froala/ember-froala-editor/assets/96573042/c2adcb4c-19eb-4dcf-8ef9-4ee267033838">

**Comment by Panman82** [comment]
Hi @kundanSinghFworks, this repo is specifically for ember.js integration but your issue seems to be general functionality with the Froala Editor itself (can't fix that type of issue with integration functionality). I'd suggest posting this over on the `froala-editor` repo instead: https://github.com/froala/wysiwyg-editor/issues

**Comment by kundanSinghFworks** [comment]
Hi @Panman82 ,

Thanks for the reply. I will be filing the issue there.
