### ISSUE TITLE
initOnClick should insert cursor at mouse click location, as default Froala editor does

### ISSUE THREAD

**Issue by chrischambers** [froala/ember-froala-editor#27]
If you view the froala [example documentation](https://www.froala.com/wysiwyg-editor/examples/init-on-click), clicking on the "z" in "initialize" will initialise the editor, focus the editor and place the cursor after the 'z' character.

On the other hand, if you visit Ember Froala' s [hide-on-blur](http://froala.github.io/ember-froala-editor/#/addon/concepts#hide) and click anywhere on "Click here for an example", the editor isn't focused immediately and it requires a second click. This also ruins the user experience for hide-on-blur, as the editor only successfully hides if the user does perform the second click.

**Comment by Panman8201** [comment]
Humm... there does seem to be a disconnect somewhere in there. I'm unsure what could be causing that since `initOnClick` is a froala editor option and isn't "used" anywhere in the ember component.

Personally, I've moved away from the `initOnClick` and `hide-on-blur` solution because of general bugginess and a data-loss bug that bit me in the...

I'll do some digging. It looks like there might be some froala editor GitHub issues that might relate here.

**Comment by chrischambers** [comment]
> Personally, I've moved away from the initOnClick and hide-on-blur solution because of general bugginess and a data-loss bug that bit me in the...

I'd be interested in the particulars - it seems like the perfect solution for my company's internal document generation application!

**Comment by Panman8201** [comment]
Yeah, it's a cool "feature" to only show the editing tools when needed. The specific related issues are;

froala/ember-froala-editor#19
froala/wysiwyg-editor#1586
froala/wysiwyg-editor#1504

All of those have since been fixed.

**Comment by Panman8201** [comment]
FYI, I'm trying to setup an ember-twiddle so we can play around with different scenarios, but there is an [issue with twiddle's build process for addons that specify environment specific assets](https://github.com/ember-cli/ember-twiddle/issues/519).

Also updated the froala-editor version to 2.4.1 and still experiencing this issue on the docs Website. Just not sure where the issue lies just yet.

**Comment by Panman8201** [comment]
FYI, figured out the problem. Setting the "html" on the init hook basically negates the focus and mucks some stuff up. I'll dig in to figure out what's needed to fix it.

https://github.com/froala/ember-froala-editor/blob/v2.4.2/addon/components/froala-editor.js#L311
