### ISSUE TITLE
Update to V2.4.2.

### ISSUE THREAD

**Issue by stefanneculai** [froala/ember-froala-editor#29]
@Panman8201 can we update this to V2.4.2? It contains an important update: https://www.froala.com/wysiwyg-editor/changelog.

**Comment by Panman8201** [comment]
Sure. I've changed this addon to use npm instead of bower for froala-editor files. So when releasing new versions you only need to [update the `package.json` dependency](https://github.com/froala/ember-froala-editor/blob/v2.4.2-beta.1/package.json#L63).

Do you want to do this release? Or else I can certainly take care of it.

**Comment by stefanneculai** [comment]
Please go ahead. Thanks!

**Comment by Panman8201** [comment]
All done.
