### ISSUE TITLE
Cannot fire on-initialized action

### ISSUE THREAD

**Issue by Shak-eah** [froala/ember-froala-editor#34]
As per the docs, any event for the froala editor listed here 

https://www.froala.com/wysiwyg-editor/docs/events#initialized

can be used via ember by using an 'on' prefix. I'm working with this package right now in the following manner:

> {{froala-editor params=froalaEditor.params value=model.html on-initialized=(action "integrate") focus=(action "froalaFocus")}}

My froalaFocus action is firing fine when the editor is focused on, but the initialized action (i.e. integrate) never fires. What am I missing?

**Comment by Panman8201** [comment]
Based on your example, it looks like you are using the [old version of the ember-froala addon](https://github.com/froala/ember-froala). The usage in this newer addon should look something like;

```hbs
{{froala-editor
  options=froalaEditor.params
  content=model.html
  on-initialized=(action "integrate")
  on-focus=(action "froalaFocus")
}}
```

Basically;
* `params` > `options`
* `value` > `content`
* `focus` > `on-focus`

But to your issue, I'm wondering if you're running into a [bug with the current version](https://github.com/froala/ember-froala-editor/issues/32). Should be fixed in the next release but try switching back to 2.5.1. `"ember-froala-editor": "~2.5.1"`

**Comment by Panman8201** [comment]
@Shak-eah we just released a new version that fixed a bug. Can you update the the latest version `2.6.1` and ensure your using the `{{froala-editor}}` properly (example in my previous post). Please get back so I know if your issue is resolved or not. Thanks!

**Comment by Shak-eah** [comment]
Ah. Thanks very much Ryan! I am unable to check immediately as I created an extended version of the component for that unfortunately time-sensitive issue, but as soon as I've tested this new library version and confirmed whether it's working or not, I will update it here!

**Comment by Panman8201** [comment]
I'm going to close this for now. If you find that it's still not working for you, feel free to write back and I'll re-open.
