### ISSUE TITLE
How can I set custom events like options in environment.js?

### ISSUE THREAD

**Issue by krnbatta** [froala/ember-froala-editor#39]

**Comment by Panman8201** [comment]
The proper way to handle this would be to use the [defaults concept](http://froala.github.io/ember-froala-editor/#/addon/concepts?section=defaults), extending the `{{froala-editor}}` and applying your default options and event handlers there. Is there a reason why you are trying to do this in `config/environment.js`? Technically only the `key` is supported in `config/environment.js`, other options just happen to work because of the way it's implemented, but that isn't documented.

**Comment by Panman8201** [comment]
I'm going to close this due to no response. But feel free to write back and I can re-open.
