### ISSUE TITLE
Interact with the editor during automated tests

### ISSUE THREAD

**Issue by viniciussbs** [froala/ember-froala-editor#45]
I'm writing automated tests for my app. When I need to fill a regular input, I write this:

```elixir
fill_in(session, fillable_field("Title"), with: "Awesome Post")
```

This will search for inputs or textareas with a placeholder `"Awesome Post"` or with a label with the same text.

```html
<label for="post-title">Title</label>
<input id="post-title">
```
```html
<input id="post-title" placeholder="Titlte">
```

I can't make labels work with a Froala editor, so I'm relying on placeholders to write my tests using my own helper to find Froala.

```elixir
fill_in(session, Froala.field("Title"), with: "Awesome Post")
```

The issue is when I'm editing a post, because the HTML element with the placeholder text is not attached to the DOM, so I can't search using the text. So, when I'm editing, I need to search for the content

```elixir
fill_in(session, Froala.field("Awesome Post"), with: "Great Post")
```

For me, the best solution would be having labels working properly. I guess the lack of working labels can be an accessibility issue. But, alternatively, having the placeholder text as data attribute while it's not visible would help.

**Comment by Panman8201** [comment]
Funny thing, the latest release includes an [acceptance test helper for the editor](https://github.com/froala/ember-froala-editor#test-helper) thanks to @rubycalling. Will this fill your needs?

I think it would be possible to make the `{{froala-editor}}` use a `<textarea>` instead of `<div contenteditable>`. That way you could attach a `<label>`. I haven't explored this option yet but we could try...

**Comment by Panman8201** [comment]
I also wanted to point out that Froala Editor itself is "accessible";

Number 6 in the list below
https://www.froala.com/blog/wysiwyg-editor/common-wysiwyg-html-editor-myths

And
https://www.froala.com/wysiwyg-editor/accessibility

**Comment by viniciussbs** [comment]
> Funny thing, the latest release includes an acceptance test helper for the editor thanks to @rubycalling. Will this fill your needs?

Sorry, I forgot to mention that I'm writing end-to-end tests with Wallaby - a Elixir solution on top of Selenium - to tests 2 single Ember apps interacting with each other and an external API, so Ember tests helpers won't help in this case.

> I think it would be possible to make the {{froala-editor}} use a <textarea> instead of <div contenteditable>. That way you could attach a <label>. I haven't explored this option yet but we could try...

That would be awesome.

> I also wanted to point out that Froala Editor itself is "accessible";

Good to know. I'll share these links with my team.

**Comment by Panman8201** [comment]
I was able to get a `<textarea>` to work with `{{froala-editor}}` but come to find out a `<label>` tag [doesn't properly focus the editor when clicked](https://jsfiddle.net/Panman8201/dg0mmz87/). So I've started a [issue with froala](https://github.com/froala/wysiwyg-editor/issues/2115) to see what the expectation is with labels.

However, I'm not sure that your `fill_in()` test helper is even going to work for the froala editor. Because the editor creates its own DOM for the editor and doesn't really monitor the `<textarea>`. I've created a [JS Fiddle highlighting this use case](https://jsfiddle.net/Panman8201/cmczo02o/). You'll probably need to integrate the test helper deeper with the [Froala Editor methods](https://www.froala.com/wysiwyg-editor/docs/methods) to accomplish your needs. For example, our [built-in helper uses the `'html.set'` method to "fill-in" the input](https://github.com/froala/ember-froala-editor/blob/master/addon-test-support/helpers/fill-in-froala-editor.js#L15).

**Comment by viniciussbs** [comment]
I fill in Froala today sending keys to the element, so that's not the problem. The problem is to find the element in a elegant way since I can't rely on the label. I was relying on the placeholder, but it is not rendered when the component is initiated with some content.

**Comment by Panman8201** [comment]
Can you target based on a selector string? All `{{froala-editor}}` instances have a class of `.froala-editor-container`, which then has a nested `<div>` with `.froala-editor-instance` (which is the *actual* froala editor instance). You can also give the editor an id and target it that way; `{{froala-editor id="foobar"}}` targeted with `#foobar .froala-editor-instance`

**Comment by viniciussbs** [comment]
> Can you target based on a selector string?

Yep. I'm already relying on that. But I would like to have content driven steps, not implementation driven steps.

This works today:

```elixir
fill_in(session, Froala.field("Title"), with: "Awesome Post")
```

It works because `"Title"` is the `placeholderText` and I use this XPath selector:

```elixir
"""
.//*[contains(./@class, 'froala-editor-container')]
    [contains(normalize-space(string(.)), '#{text}') or contains(normalize-space(string(.)), '#{value}')]
    //*[contains(./@class, 'fr-element')]
"""
```

But, when I try to fill an already filled Froala instance, it doesn't work:

```elixir
fill_in(session, Froala.field("Title"), with: "Edited Post") # There's no "Title" in DOM
```

So, today, when I want to test editing, I'm using a different helper:

```elixir
fill_in(session, Froala.field("Title", value: "Awesome Post"), with: "Edited Post")
```

Now it works because I use this XPath selector when `value` is passed:

```elixir
"""
.//*[contains(./@class, 'froala-editor-container')]
    [contains(normalize-space(string(.)), '#{text}') or contains(normalize-space(string(.)), '#{value}')]
    //*[contains(./@class, 'fr-element')]
"""
```

I wouldn't need to pass the `value` if the placeholder text were always present in DOM.

**Comment by Panman8201** [comment]
I'm assuming you would rather write a helper that;

1. Clicks on a `<label>` which then focuses on an input element
2. Fire off some key strokes and test to see if input is taking effect

Rather than writing a test that works with DOM directly.

[I tried to do something similar in an ember integration test but it didn't work as expected.](https://github.com/froala/wysiwyg-editor/issues/1718) While I could add a `{{froala-label}}` that would function like a `<label>` when clicked, I'm not sure if that'll work either. You might need to consult with Froala directly on how to make this type of test work.

**Comment by Panman8201** [comment]
Closing for now. If you have further details here I can certainly re-open, but I think it gets back to  how the editor itself works with labels.
