### ISSUE TITLE
Consider using `ember-auto-import`

### ISSUE THREAD

**Issue by sreeram-cv** [froala/ember-froala-editor#92]
Hi,

If we can use ember-auto-import to import the froala npm package, plugins and languages instead of ember-cli `this.import`, that will be of great help to us in reducing the vendor file size.

Thanks,
Sreeram

**Comment by Panman82** [comment]
Yeah, I had tried to make this happen but the plugins must be imported in a certain order (mainly before the editor). With previous versions of this addon, this was all taken care for you, but maybe instead it would be better (and more future proof) to require apps to extend the addon and import the plugins needed. I'll have to play around with this approach, but if you have other ideas please let me know.

**Comment by Panman82** [comment]
*FYI, I linked to this issue on the latest release, to gather more feedback on this topic.*

Thinking this through a bit more, I'm not sure what would be better. There are a few things to consider;

1. The editor needs to be imported before the plugins
2. Plugins might have CSS to be included as well
3. Custom editor buttons and such work well in an ember initializer

So by moving to `ember-auto-import`, I foresee the following being required;

1. Apps would need to extend the editor component to import the plugins/languages needed
2. Apps would need to import the main CSS files and plugin CSS individually
3. Apps would need to extend the editor component to create custom buttons and such

So the DX of moving to `ember-auto-import` would be worse IMO, since a lot of that stuff is taken care of by the addon currently. However, this might be the best direction anyway, with template imports and Embroider both coming soon. Just not sure, open to feedback. Thanks!

**Comment by sreeram-cv** [comment]
Hi,
I get your point. thanks for the reply.

**Comment by Panman82** [comment]
Need to start working on this, required to reach embroider compatibility and will benefit going to ember v4.
